#!/bin/bash
[ "$VERBOSE" ] && set -x
set -uo pipefail

if git -C clone rev-parse &>/dev/null; then
  git clone ./clone ./output
else
  cp -R clone/. output/
fi

for FILE in ${INPUT_FILES}; do
  SOURCE="${FILE/:*/}"
  TARGET="${FILE/*:/}"
  cp -prv "${SOURCE}" "output/${TARGET}"
done
