#!/bin/bash
[ "$VERBOSE" ] && set -x
set -uo pipefail

if git -C input1 rev-parse &>/dev/null; then
  git clone ./input1 ./output
else
  cp -R input1/. output/
fi

for FILE in ${INPUT_FILES}; do
  SOURCE="${FILE/:*/}"
  TARGET="${FILE/*:/}"
  cp -prv "${SOURCE}" "output/${TARGET}"
done
