#!/bin/bash
[ "$VERBOSE" ] && set -x
set -uo pipefail

git clone ./input ./output

cd output
git config user.email "${GIT_COMMIT_EMAIL}"
git config user.name  "${GIT_COMMIT_NAME}"
git add .
git commit -m "${GIT_COMMIT_MESSAGE}" || false
