---
resources:

- name: config-hydrated
  type: git
  source:
    <<: &config-resource
      uri: git@github.com:jpluscplusm/concourse-test.git
      branch: master
      private_key: {{privkey}}
    paths: [ result/* ]

- name: config-template
  type: git
  source:
    <<: *config-resource
    ignore_paths: [ result/* ]

jobs:

- name: change-repo
  plan:

  - get: repo
    resource: config-template
    trigger: true

  - task: change-file
    file: repo/change-file.yml

  - task: combine-inputs
    file: repo/combine-inputs.yml
    input_mapping: {this: repo, clone: repo, input1: changed, input2: changed}
    output_mapping: {output: combined-input}
    params:
      INPUT_FILES: "input2/date:result/date input2/date:result/testofnewfile"

  - try:

      task: git-commit
      file: repo/git-commit.yml
      input_mapping:  {this: repo, input: combined-input}
      output_mapping: {output: dir-with-commit}
      params:
        GIT_COMMIT_EMAIL: "contact@jpluscplusm.com"
        GIT_COMMIT_NAME: "Jonathan Matthews"
        GIT_COMMIT_MESSAGE: "Commit inside CI"
      on_success:
        put: config-hydrated
        params: {repository: dir-with-commit}

- name: consume-result
  plan:
  - get: repo
    trigger: true
    resource: config-hydrated
    passed: [change-repo]
  - task: report-file
    file: repo/report-file.yml
