---
resources:

- name: config-dummy-git-resource
  type: git
  check_every: 65535h # because "never" isn't valid ...
  source: &config-resource
    uri: git@github.com:jpluscplusm/concourse-test.git
    branch: master
    private_key: {{privkey}}

- name: config-hydrated
  type: git
  source:
    <<: *config-resource
    paths: [ result/* ]

- name: config-template
  type: git
  source:
    <<: *config-resource
    ignore_paths: [ result/* ]

groups:
- name: default
  jobs: 
  - change-repo
  - consume-result

jobs:

- name: change-repo
  plan:

  - get: repo
    resource: config-template
    trigger: true

  - task: change-file
    file: repo/change-file.yml

  - task: combine-inputs
    file: repo/combine-2-inputs.yml
    input_mapping: {this: repo, input1: repo, input2: changed}
    output_mapping: {output: combined-input}
    params:
      INPUT_FILES: "in1/date:result/date in1/date:result/testofnewfile"

  - try:

      task: git-commit
      file: repo/git-commit.yml
      input_mapping:  {this: repo, input: combined-input}
      output_mapping: {output: dir-with-commit}
      params:
        GIT_COMMIT_EMAIL: "contact@jpluscplusm.com"
        GIT_COMMIT_NAME: "Jonathan Matthews"
        GIT_COMMIT_MESSAGE: "Commit inside CI"
      on_success:
        put: config-hydrated
        params: {repository: dir-with-commit}

- name: consume-result
  plan:
  - get: repo
    trigger: true
    resource: config-hydrated
    passed: [change-repo]
  - task: report-file
    file: repo/report-file.yml

- name: dummy-resource-consumer
  plan:
  - get: config-dummy-git-resource

